#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { Command } from "commander";
import { designTokensSchema } from "./tokens-schema.js";

function toTailwindConfig(tokens: ReturnType<typeof designTokensSchema.parse>): string {
  const colorEntries = Object.entries(tokens.colors)
    .map(([key]) => `        ${key}: "var(--color-${key})",`)
    .join("\n");

  return `// Generated by ui-toolkit/scripts/src/generate-tailwind-config.ts
// Import tokens.css (from generate-tokens.ts) wherever this config's CSS is loaded,
// so the CSS custom properties referenced below are defined at runtime.
import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
${colorEntries}
      },
      fontFamily: {
        display: ["${tokens.fonts.display}", "sans-serif"],
        body: ["${tokens.fonts.body}", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
      },
    },
  },
  plugins: [],
} satisfies Config;
`;
}

async function main() {
  const program = new Command();
  program
    .requiredOption("--tokens <file>", "Path to a tokens.json file (from generate-tokens.ts)")
    .option("--out <file>", "Output path", "./tailwind.config.ts")
    .parse(process.argv);

  const opts = program.opts<{ tokens: string; out: string }>();
  const raw = JSON.parse(await readFile(opts.tokens, "utf8"));
  const tokens = designTokensSchema.parse(raw);

  await writeFile(opts.out, toTailwindConfig(tokens), "utf8");
  console.log(`Wrote ${opts.out}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
